sudo: required
dist: trusty
language: node_js
node_js:
- '4.2'
- '0.12'
- '0.11'
- '0.10'
services:
- redis-server
script: npm test
after_script: npm run test-coverage && cat ./coverage/lcov.info | coveralls
after_success: script/gh-pages.sh
