sudo: required
dist: trusty
language: node_js
node_js:
- '4'
- '5'
- '6'
services:
- redis-server
script: npm test
after_script: npm run test-coverage && cat ./coverage/lcov.info | coveralls
after_success: script/gh-pages.sh
env:
  global:
    secure: dB88c+D+JYiwV4VA08ClqoRTYhnLFZssQZZE45SLKNGJo5wNv8DQYaCfWCCv4EJW4pNXK/2l3B+EmCdMiVj1knhfaDaDflGoTIvIPNcvmCBK3kbyks3sn4RyUaL3EGsqhWvhUzFZyf+RDvBrrkhbYmSBOodUtdMUcqsbX6Z2+NGUzA5UHhetE1zXBWUq/Qn0ffm0HQt7Fn2MlX+cJOGS4R43aF0PSauqp2mQB1UVCT3l6ph3LjG1PfHjgZRS5KQwvyGyaXsJM4A6esUA1I0pn3rwMybPgZgjo5b4oHJPb9S4lZ1TfflRl2SaxregeAeUAJdd98pK4IW7Qnyma6TUf2t1Aa7tYO9qZy7gqDvR8HnLwbU9oFyXi4IaPl9X3WihHMsJ/sjR1lAgcgpjpmQBtsz42Is495TPZA9JssTJCJdvSKgwgQ9M+CxvtLaGRLp7yl6Ax1+FMU9fv/awj2jal27Tl5IDZHVCkWOxx1RjIuvWaR+Xi5lE+UQMSIku3EWILhGGgSOKHGBjvHdrVU1ZmhyupDwA5afArwv630vlFXKANmH82S+5XxNtt1qdK74BD1tz1bAeTC0i7uAEHHT2VupuaUAdg+EhPigI4RSLRbmoIFL+l9Lxy7u7ycgDScXBDVHZdoR+1hdMnGIiqx+vW1PR8efZIYoUvFc05R1M2oc=
